name: Auto Login

on:
  schedule:
    - cron: "30 3 * * 1-6"
    - cron: "30 15 * * 1-6"
  workflow_dispatch:  # Allow manual trigger for testing

jobs:
  run-login:
    runs-on: ubuntu-latest

    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium
          pip install webdriver-manager  # Helps manage ChromeDriver

      - name: Run Login Script
        run: python login.py
